[meta]
  title = "C# Live Text-to-Speech Starter"
  description = "Get started using Deepgram's Live Text-to-Speech with this C# demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "Live"
  language = "C#"
  framework = ".NET"

[build]
  command = "dotnet restore"

[config]
  sample = ".env-sample"
  output = ".env"

[post-build]
  message = "dotnet run"
