[meta]
  title = "Live TTS .NET Starter"
  description = "Basic demo for using Deepgram TTS Live/WebSockets with .NET"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "TTS WebSockets"
  language = "C#"
  framework = ".NET"

[build]
  command = "dotnet restore"

[config]
  sample = ".env-sample"
  output = ".env"

[post-build]
  message = "dotnet run"
